In [5]:
# pip show numpy

In [7]:
import numpy as np 
np.random.seed(0) 
x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5)) 
print("x1 ndim: ", x1.ndim) 
print("x2 shape:", x2.shape) 
print("x3 size: ", x3.size) 

x1 ndim:  1
x2 shape: (3, 4)
x3 size:  60


In [11]:
import numpy as np 
x1 = np.random.randint(10, size=6) 
print('array') 
print(x1) 
print('select an element from an array') 
print(x1[0]) 
print('select an element by negative index') 
print(x1[-3])

array
[4 3 4 4 8 4]
select an element from an array
4
select an element by negative index
4


In [13]:
import numpy as np 
x1 = np.random.randint(12, size=(3,4)) 
print('array') 
print(x1) 
print('select an element from an array') 
print(x1[1,2]) 

array
[[ 3 10  7  5]
 [ 5  0  1  5]
 [ 9  3  0  5]]
select an element from an array
1


In [16]:
import numpy as np 
print('A sequence Array') 
x = np.arange(10) 
print(x) 
print('Slice first 3 values') 
print(x[:3]) 
print('Slice elements after index 7') 
print(x[7:]) 
print('slice middle values') 
print(x[4:7]) 
print('slice every second element') 
print(x[::2]) 

A sequence Array
[0 1 2 3 4 5 6 7 8 9]
Slice first 3 values
[0 1 2]
Slice elements after index 7
[7 8 9]
slice middle values
[4 5 6]
slice every second element
[0 2 4 6 8]


In [18]:
import numpy as np 
x = np.random.randint(10, size=(3, 4)) 
print('Array',x2) 
print('Slice two rows and three columns') 
print(x[:2,:3]) 
print('Slice three rows and two columns') 
print(x[:3,::2]) 
print('Slice a particular value') 
print(x[:1,:1])

Array [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Slice two rows and three columns
[[0 1 2]
 [2 0 3]]
Slice three rows and two columns
[[0 2]
 [2 3]
 [0 5]]
Slice a particular value
[[0]]


In [20]:
import numpy as np 
x=np.arange(1,10) 
print('Array',x) 
x1=x.reshape(3,3) 
print('Reshaped Array') 
print(x1) 

Array [1 2 3 4 5 6 7 8 9]
Reshaped Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
import numpy as np 
x=np.array([1,2,3,4,5]) 
y=np.array([6,7,8,9,10]) 
print('X=',x) 
print('Y=',y) 
print('Array Concatenation') 
z=np.concatenate([x,y]) 
print('Z=',z) 
print('Array Splitting') 
x1,x2=np.split(z,[3]) 
print('X1=',x1) 
print('X2=',x2) 

X= [1 2 3 4 5]
Y= [ 6  7  8  9 10]
Array Concatenation
Z= [ 1  2  3  4  5  6  7  8  9 10]
Array Splitting
X1= [1 2 3]
X2= [ 4  5  6  7  8  9 10]
